# Lecture 9/6/2024

In [3]:
#!pip install tensorflow

In [26]:
import tensorflow as tf
import keras as keras
import numpy as np

In [5]:
print("tensorflow.ver:", tf.__version__)
print("keras_ver.:", keras.__version__)

tensorflow.ver: 2.17.0
keras_ver.: 3.5.0


In [2]:
import sys

print("Python ver.:", sys.version)

Python ver.: 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]


## Simple NN (Perceptron) with 4 inputs

In [28]:
# simple NN (Perceptron) with 4 inputs
inputs = [1, 2, 3, 4.5] # <- this is an array
weights = [0.2, 0.8, -0.5, 1]
bias = 2

# the output is a LC of inputs and weights + bias
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias
print(output)

lc = np.dot(inputs, weights) + bias
print(lc)

6.8
6.8


What about if there are 4 inputs with 3 neurons?

In [29]:
# 4 inputs and 3 neurons
# there are 3 sets per weight
inputs = [1, 2, 3, 2.5] # <- this is an array

weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

# need 1 bias per neuron, so we need 3 neurons
bias1 = 2
bias2 = 3
bias3 = 0.5

# use list to obtain output
# in python, a list is just a matrix
output = [
    inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
    inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
    inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3
]
print(output)


[4.8, 1.21, 2.385]


We can convert the 3 weights into one matrix; same thing with the bias

In [21]:
# use weights and bias in list format
# shape of weights: (3,4) or [3 x 4]: 2D array (matrix)
weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2, 0.3, 0.5]
# shape of biases: (1,3) or [1 x 3]

Linear combination is the **dot product**!!

In [33]:
# employ dot product
import numpy as np

output = np.dot(inputs, weights) + biases
print(f"np output: {output}") # <- this is called an f-string!!

np output: [4.8 3.1 3.3]


## Forward Propagation vs Backpropagation

#### Forward Propagation
- In forward propagation, the neural network processes input data by passing it through the layers of the network. Each layer applies weights and biases to the inputs, and then an activation function produces the output.
- **Purpose**: It calculates the predicted output using the initial weights and biases. No learning or adjustments happen during this phase.
- **Process**: Inputs → Weights & Biases → Activation → Output (Prediction)
- This phase doesn't involve corrections but simply computes the output based on the current state of the network.

#### Backpropagation
- Backpropagation is the process where the neural network learns by correcting errors. It calculates the gradient of the loss function with respect to each weight by using the chain rule.
- **Purpose**: It updates the weights and biases by minimizing the error between the predicted output and the actual output using techniques like gradient descent.
- **Process**: Error (Loss) is propagated back through the network → Calculate gradients → Adjust weights and biases to reduce error.



## Forward propogation in ANN

In [58]:
# import numpy as np

weights = np.around(np.random.uniform(size=6), decimals=4)
biases = np.around(np.random.uniform(size=3), decimals=4)

print(weights)
print(biases)

# inputs
x_1 = 0.5 # input 1
x_2 = 0.85 # input 2

print(f"x1 is {x_1} and x2 is {x_2}")

[0.1376 0.5652 0.2006 0.037  0.4463 0.4771]
[0.3699 0.8701 0.5704]
x1 is 0.5 and x2 is 0.85


In [70]:
# z_11 = x1w1 + x2w2 + b11
z_11 = x_1 * weights[0] + x_2 * weights[1] + biases[0]
# np.around(z_11, decimals=4)
print(f"The weighted sum of the inputs at the first node in the hidden layer is {z_11:.4f}")
#print(f"The weighted sum of the inputs at the first node in the hidden layer is {z_11}")

The weighted sum of the inputs at the first node in the hidden layer is 0.9191


In [72]:
# z_12 = x1w3 + x2w4 + b12
z_12 = x_1 * weights[2] + x_2 * weights[3] + biases[1]
z_12 = np.around(z_12, decimals=4)
print(f"The weighted sum of the inputs at the second node in the hidden layer is {z_12}")

The weighted sum of the inputs at the second node in the hidden layer is 1.0018


$\text{Sigmoid activation function: }$ $$a(z) = \frac{1}{1 + e^{-z}}$$


In [80]:
# assuming a sigmoid activation function, let's compute the activation of the first node: a_1,1, in the hidden layer
a_11 = 1./(1+np.exp(-z_11))
print(f"The activation of the first node in the hidden layer is {a_11:.4f}")

# for a_1,2
a_12 = 1./(1+np.exp(-z_12))
print(f"The activation of the second node in the hidden layer is {a_12:.4f}")

The activation of the first node in the hidden layer is 0.7149
The activation of the second node in the hidden layer is 0.7314


In [83]:
# output layer
z_2 = a_11*weights[4] + a_12*weights[5] + biases[2]
print(f"The weighted sum at the output layer is {z_2:.4f}")

The weighted sum at the output layer is 1.2384


In [87]:
# output of the network in the output layer
a_2 = 1./(1.+np.exp(-z_2))
print(f"The output of the network for X is {a_2:.4f}")

The output of the network for X is 0.7753


In [95]:
# batches of inputs
# list of shape (3,4) input matrix
inputs = [
    [1, 2, 3, 2.5],
    [2, 5, -1, 2],
    [-1.5, 2.7, 3.3, -.8]
]

weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2, 3, 0.5]

layer_output = np.dot(inputs, np.array(weights).T) + biases
print(layer_output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [99]:
# so far, we have input layer with 4 features and a hidden layer with 3 neurons
# add another layer with 3 neurons
weights2 = [
    [0.1, -0.4, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13]
]

biases2 = [-1, 2, -0.5]

layer2_output = np.dot(layer_output, np.array(weights2).T) + biases2
print(layer2_output)

[[ 0.1885  -1.04185 -2.03875]
 [ 0.714   -2.7332  -5.7633 ]
 [-1.2664   1.41254 -0.35655]]
